#!/bin/bash

#****************************************************************************************************#
#                                           RESTORE-SNAPSHOT                                         #
#****************************************************************************************************#

#----------------------------------------------------------------------------------------------------#
# IF THE USER HAS NO ROOT PERMISSIONS THE SCRIPT WILL EXIT                                           #
#----------------------------------------------------------------------------------------------------#

if (($EUID!=0))
then
  echo "You must be root to run this script" 2>&1
  exit 1
fi

#----------------------------------------------------------------------------------------------------#
# CONFIGURATION VARIABLES                                                                            #
#----------------------------------------------------------------------------------------------------#

data_folder="/root/data"
log_file="/root/remnode.log"
config_folder="/root/config"
create_snapshot_folder="/root/data/snapshots"

#----------------------------------------------------------------------------------------------------#
# MAIN PART OF THE SCRIPT                                                                            #
#----------------------------------------------------------------------------------------------------#

if [ ! -d "$create_snapshot_folder" ]
then
  mkdir -p "$create_snapshot_folder"
  cp -p "$0" "$create_snapshot_folder"
fi
blocks_folder=$data_folder/blocks
state_folder=$data_folder/state
rm -f *.bin
latest_snapshot="2020-02-21_00-00.tar.gz"
wget -c https://www.geordier.co.uk/snapshots/$latest_snapshot -O - | sudo tar -xz --strip=4
bin_file=$create_snapshot_folder/*.bin
remnode_pid=$(pgrep remnode)
if [ ! -z "$remnode_pid" ]
then
  if ps -p $remnode_pid > /dev/null
  then
    kill -SIGINT $remnode_pid
  fi
  while ps -p $remnode_pid > /dev/null; do
  sleep 1
  done
fi
rm -rf $blocks_folder*/
rm -rf $state_folder
cd ~
remnode --config-dir $config_folder/ --snapshot $bin_file --data-dir $data_folder/ >> $log_file 2>&1 &
sleep 3
tail -f $log_file
