#!/bin/bash

#****************************************************************************************************#
#                                          RESTORE-SNAPSHOT                                          #
#****************************************************************************************************#

#----------------------------------------------------------------------------------------------------#
# IF THE USER HAS NO ROOT PERMISSIONS THE SCRIPT WILL EXIT                                           #
#----------------------------------------------------------------------------------------------------#

if (($EUID!=0))
then
  echo "You must be root to run this script" 2>&1
  exit 1
fi

#----------------------------------------------------------------------------------------------------#
# CONFIGURATION VARIABLES                                                                            #
#----------------------------------------------------------------------------------------------------#

data_folder=/root/data
log_file=/root/remnode.log
config_folder=/root/config
snapshot_folder=$data_folder/snapshots
config_file="/root/data/snapshots/config"

#----------------------------------------------------------------------------------------------------#
# MAIN PART OF THE SCRIPT                                                                            #
#----------------------------------------------------------------------------------------------------#

if grep "^testchain_enabled=true" "$config_file" > /dev/null 2>&1
then  
  if [ ! -d "$snapshot_folder" ]
  then
    mkdir -p "$snapshot_folder"
    cp -p "$0" "$snapshot_folder"
  fi
  blocks_folder=$data_folder/blocks
  state_folder=$data_folder/state
  last_download_folder=$snapshot_folder/lastdownload
  if [ ! -d "$last_download_folder" ]
  then
    mkdir -p "$last_download_folder"
    exit 1
  fi
  cd $last_download_folder
  rm -f *.bin
  latest_snapshot=$(last_download_folder)
  bin_file=$last_download_folder/*.bin
  remnode_pid=$(pgrep remnode)
  if [ ! -z "$remnode_pid" ]
  then
    if ps -p $remnode_pid > /dev/null
    then
      kill -SIGINT $remnode_pid
    fi
    while ps -p $remnode_pid > /dev/null; do
        sleep 1
    done
   fi
   rm -rf $blocks_folder*/
   rm -rf $state_folder
   cd ~
   remnode --config-dir $config_folder/ --snapshot $bin_file --data-dir $data_folder/ >> $log_file 2>&1 &
   sleep 3
   tail -f $log_file
else
  if [ ! -d "$create_snapshot_dir" ]
  then
    mkdir -p "$snapshot_folder"
    cp -p "$0" "$snapshot_folder"
  fi
  blocks_folder=$data_folder/blocks
  state_folder=$data_folder/state
  last_download_folder=$snapshot_folder/lastdownload
  if [ ! -d "$last_download_folder" ]
  then
    mkdir -p "$last_download_folder"
  fi
  cd $last_download_folder
  rm -f *.bin
  latest_snapshot=$(curl -s https://geordier.co.uk/snapshots/latestsnapshot.php)
  wget -c https://www.geordier.co.uk/snapshots/$latest_snapshot -O - | sudo tar -xz --strip=4
  bin_file=$last_download_folder/*.bin
  remnode_pid=$(pgrep remnode)
  if [ ! -z "$remnode_pid" ]
  then
    if ps -p $remnode_pid > /dev/null
    then
      kill -SIGINT $remnode_pid
    fi
    while ps -p $remnode_pid > /dev/null; do
    sleep 1
    done
  fi
  rm -rf $blocks_folder*/
  rm -rf $state_folder
  cd ~
  remnode --config-dir $config_folder/ --snapshot $bin_file --data-dir $data_folder/ >> $log_file 2>&1 &
  sleep 3
  tail -f $log_file
fi
