#!/bin/bash
###### Parameter Section #####
ssh_port=466
date_name=$(date +%Y-%m-%d_%H-%M)
sh_create=compressandsendlastsnapshot.sh
cd ~
remchain_compressed_folder=/root/data/snapshots/compressed/
testchain_compressed_folder=/root/data/snapshots/compressed/
filename="$compressedfolder$date_name.tar.gz"
mkdir -p $compressedfolder
snapname=$(curl http://127.0.0.1:8888/v1/producer/create_snapshot | jq '.snapshot_name')


rm -f $shcreate
touch $shcreate && chmod +x $shcreate

#List all .gz files especially the last 5 by filename aand remove the rest
ls -F *.gz | head -n -5 | xargs -r rm

echo "tar -cvzf $filename $snapname" >> $shcreate
rm -f $snapname
echo "rsync -rv -e 'ssh -p $sshportno' --progress $filename root@website.geordier.co.uk:/var/www/geordier.co.uk/snapshots" >> $shcreate
./$shcreate
